export const abbreviations = [
	{ short: '2M', long: 'Second Minister' },
	{ short: '2PS', long: 'Second Permanent Secretary' },
	{ short: 'A&T', long: 'Adapt and Train' },
	{ short: 'AA', long: 'Approving Authority' },
	{ short: 'AAR', long: 'After Action Review' },
	{ short: 'ABC', long: 'Active, Beautiful, Clean Waters' },
	{ short: 'ABC', long: 'AI, Blockchain, Chatbot' },
	{ short: 'ABCD', long: 'Analytics, Blockchain, Cloud, Data' },
	{ short: 'ACCSM', long: 'ASEAN Conference on Civil Service Matters' },
	{ short: 'ACD', long: 'Audit and Compliance Department' },
	{ short: 'ACDT', long: 'Australian Central Daylight Savings' },
	{ short: 'ACE', long: 'Achieving Continuous Excellence' },
	{ short: 'ACE', long: 'Assistant Chief Executive' },
	{ short: 'ACL', long: 'Access Control List' },
	{ short: 'ACRA', long: 'Accounting and Corporate Regulatory Authority' },
	{ short: 'ACST', long: 'Australian Central Standard Time' },
	{ short: 'ACT', long: 'Align, Communicate & Take Ownership' },
	{ short: 'ACT', long: 'Application Compatibility Testing' },
	{ short: 'ACTEP', long: 'Advanced Certificate in Technical Education Pedagogy' },
	{ short: 'AD', long: 'Active Directory' },
	{ short: 'ADDD', long: 'Application Design, Development & Deployment' },
	{ short: 'ADP', long: 'Agency Digitalisation Plans' },
	{ short: 'ADRO', long: 'Assistant Digital Records Officer' },
	{ short: 'ADT', long: 'Atlantic Daylight Time' },
	{ short: 'ADWI', long: 'Adaptive Digital Workplace Infrastructure' },
	{ short: 'AEDT', long: 'Australian Eastern Summer Time' },
	{ short: 'AEP', long: 'Annual Engagement Plan' },
	{ short: 'AES', long: 'Advanced Encryption Standard' },
	{ short: 'AEST', long: 'Australian Eastern Standard Time' },
	{ short: 'AFI', long: 'Area For Improvement' },
	{ short: 'AFM', long: 'Agency Facility Management' },
	{ short: 'AFT', long: 'Afghanistan Time' },
	{ short: 'AGC', long: "Attorney-General's Chambers" },
	{ short: 'AGD', long: "Accountant-General's Department" },
	{ short: 'AGO', long: "Auditor-General's Office" },
	{ short: 'AGV', long: 'Automated Guided Vehicle' },
	{ short: 'AI', long: 'Application Infrastructure' },
	{ short: 'AI', long: 'Artificial Intelligence' },
	{ short: 'AIAS', long: 'Application Infrastructure Architecture Standards' },
	{ short: 'AIAS', long: 'Application Infrastructure Architecture Standard' },
	{ short: 'AIISA', long: 'Agency ICT Infrastructure Security Assessment' },
	{
		short: 'AIM Model',
		long: 'Analytical and Intellectual Capacity Influence and Collaboration Motivation for Excellence',
	},
	{ short: 'AIP', long: 'Approval In Principal' },
	{ short: 'AIaaB', long: 'AI as a Business' },
	{ short: 'AKA', long: 'Also Known As' },
	{ short: 'AKST', long: 'Alaska Standard Time' },
	{ short: 'ALP', long: 'Applied Learning Programme' },
	{ short: 'AMAP', long: 'Active Mobility Advisory Panel' },
	{ short: 'AMP', long: 'Active Mobility Patrol' },
	{ short: 'AMR', long: 'Autonomous Mobile Robots' },
	{ short: 'AMS', long: 'Asset Management System' },
	{ short: 'AMST', long: 'Amazon Summer Time' },
	{ short: 'AMT', long: 'Armenia Time' },
	{ short: 'AMT', long: 'Amazon Time' },
	{ short: 'ANCP', long: 'Application Network Connectivity Plan' },
	{ short: 'ANPR', long: 'Automatic Number Plate Recognition' },
	{ short: 'AO', long: 'Approving Officer' },
	{ short: 'AO', long: 'Administrative Officer' },
	{ short: 'AOB', long: 'Any Other Business' },
	{ short: 'AOI', long: 'Areas Of Improvement' },
	{ short: 'AOR', long: 'Approval Of Requirement' },
	{ short: 'APA', long: 'Annual Performance Appraisal' },
	{ short: 'APEX', long: 'API Gateway' },
	{ short: 'API', long: 'Application Programming Interface' },
	{ short: 'APIX', long: 'API eXchange' },
	{ short: 'APPLES', long: 'Application for Passport On-line Electronic System' },
	{ short: 'APPS', long: 'Automated Precast Production System' },
	{ short: 'APV', long: 'Approved Procurement Value' },
	{ short: 'AR', long: 'Augmented Reality' },
	{ short: 'AR', long: 'Ad-hoc Request' },
	{ short: 'ARC', long: 'Audit Risk Committee' },
	{ short: 'ARR', long: 'Accounting Rate of Return' },
	{ short: 'ART', long: 'Argentina Time' },
	{ short: 'ASA', long: 'Annual Security Assessment' },
	{ short: 'ASAP', long: 'As Soon As Possible' },
	{ short: 'ASAS', long: 'Advertising Standards Authority of Singapore' },
	{ short: 'ASM', long: 'Application Services Manager' },
	{ short: 'ASO', long: 'Administrative Support Officer' },
	{ short: 'ASPIRE', long: 'Applied Study in Polytechnics and ITE Review' },
	{ short: 'AST', long: 'Atlantic Standard Time' },
	{ short: 'AST', long: 'Arabia Standard Time' },
	{ short: 'ASTAR', long: 'Agency For Science, Technology And Research' },
	{ short: 'ASTAR', long: 'Agency for Science, Technology and Research' },
	{ short: 'ATFM', long: 'Air Traffic Flow Management' },
	{ short: 'AUC', long: 'Asset Under Construction' },
	{ short: 'AUP', long: 'Acceptable Use Policy' },
	{ short: 'AUT', long: 'Automatic Utensils Trolley' },
	{ short: 'AVA', long: 'Agri-Food & Veterinary Authority of Singapore' },
	{ short: 'AWOL', long: 'Absent Without Leave' },
	{ short: 'AWS', long: 'Annual Wage Supplement' },
	{ short: 'AWS', long: 'Amazon Web Services' },
	{ short: 'AWST', long: 'Australian Western Standard Time' },
	{ short: 'AgTM', long: 'Agency Technical Meeting' },
	{ short: 'B2B', long: 'Business-to-Business' },
	{ short: 'B2C', long: 'Business-to-Commerce' },
	{ short: 'BA', long: 'Business Analyst' },
	{ short: 'BAD', long: 'Business Analyst, Domain' },
	{ short: 'BAF', long: 'Business Analyst, Functional' },
	{ short: 'BC/DR', long: 'Business Continuity and Disaster Recovery' },
	{ short: 'BCA', long: 'Building and Construction Authority' },
	{ short: 'BCM', long: 'Business Continuity Management' },
	{ short: 'BCP', long: 'Business Continuity Plan' },
	{ short: 'BCS', long: 'Business Card System' },
	{ short: 'BD', long: 'Business Development' },
	{ short: 'BDT', long: 'Brunei Time' },
	{ short: 'BEO', long: 'Block Exemption Order' },
	{ short: 'BGP', long: 'Business Grants Portal' },
	{ short: 'BH', long: 'Berita Harian' },
	{ short: 'BI', long: 'Business Insights' },
	{ short: 'BI', long: 'Behavioural Indicator' },
	{ short: 'BIM', long: 'Building Information Modelling' },
	{ short: 'BIOME', long: 'Biodiversity and Environment database system' },
	{ short: 'BIOT', long: 'British Indian Ocean Time' },
	{ short: 'BIT', long: 'Baker Island Time' },
	{ short: 'BIl', long: 'Business impact level' },
	{ short: 'BMS', long: 'Building Management System' },
	{ short: 'BOT', long: 'Bolivia Time' },
	{ short: 'BPI', long: 'Business Process Improvement' },
	{ short: 'BPO', long: 'Business Process Outsourcing' },
	{ short: 'BPR', long: 'Business Process Re-engineering' },
	{ short: 'BQ', long: 'Budgetary Quotation' },
	{ short: 'BRST', long: 'Braslia Summer Time' },
	{ short: 'BRT', long: 'Brasilia Time' },
	{ short: 'BSC', long: 'Balanced Scorecard' },
	{ short: 'BSEP', long: 'Bus Service Enhancement Programme' },
	{ short: 'BST', long: 'Bangladesh Standard Time' },
	{ short: 'BTT', long: 'Bhutan Time' },
	{ short: 'BYOD', long: 'Bring Your Own Device' },
	{ short: 'CAAS', long: 'Civil Aviation Authority of Singapore' },
	{ short: 'CAB', long: 'Cabinet' },
	{ short: 'CAG', long: 'Changi Airport Group' },
	{ short: 'CAGE', long: 'Cybersecurity Assessment of Government Environment' },
	{ short: 'CAPAM', long: 'Commonwealth Association of Public Administration & Management' },
	{ short: 'CAPEX', long: 'Capital Expenditure' },
	{ short: 'CAPTCHA', long: 'Completely Automated Public Turing test to tell Computers and Humans Apart' },
	{ short: 'CARE', long: 'Caring Actions in Response to Emergency' },
	{ short: 'CASE', long: 'Consumers Association of Singapore' },
	{ short: 'CAT', long: 'Central Africa Time' },
	{ short: 'CBP', long: 'Community Based Programme' },
	{ short: 'CBT', long: 'Computer Based Training' },
	{ short: 'CBTC', long: 'Communications-Based Train Control' },
	{ short: 'CC', long: 'Commercial Cloud' },
	{ short: 'CCCS', long: 'Competition and Consumer Commission of Singapore' },
	{ short: 'CCDG', long: 'Connectivity Competition Development Group' },
	{ short: 'CCOD', long: 'Corporate Culture and Organisation Development' },
	{ short: 'CCS', long: 'Competition Commission Of Singapore' },
	{ short: 'CCT', long: 'Cocos Islands Time' },
	{ short: 'CD', long: 'Cluster Director' },
	{ short: 'CDF', long: 'Chief of Defence Force, SAF' },
	{ short: 'CDG', long: 'Corporate Development Group' },
	{ short: 'CDN', long: 'Content Delivery Network' },
	{ short: 'CDO', long: 'Chief Data Officer' },
	{ short: 'CDP', long: 'Career Development Plan' },
	{ short: 'CDR', long: 'Common Data Representation' },
	{ short: 'CDSO', long: 'Chief Digital Strategy Officer' },
	{ short: 'CE', long: 'Chief Executive' },
	{ short: 'CEA', long: 'Council For Estate Agencies' },
	{ short: 'CEO', long: 'Chief Executive Officer' },
	{ short: 'CEP', long: 'Current Estimated Potential' },
	{ short: 'CERT', long: 'Computer Emergency Response Teams' },
	{ short: 'CEST', long: 'Central European Summer Time' },
	{ short: 'CET', long: 'Central European Time' },
	{ short: 'CFC', long: 'Call For Collaboration' },
	{ short: 'CFO', long: 'Chief Financial Officer' },
	{ short: 'CHADT', long: 'Chatham Daylight Time' },
	{ short: 'CHAST', long: 'Chatham Standard Time' },
	{ short: 'CHOST', long: 'Choibalsan Summer Time' },
	{ short: 'CHRO', long: 'Chief Human Resources Officer' },
	{ short: 'CHST', long: 'Chamorro Standard Time' },
	{ short: 'CHUT', long: 'Chuuk Time' },
	{ short: 'CI', long: 'Critical Infrastructure' },
	{ short: 'CIA', long: 'Confidentiality, Integrity, Availability' },
	{ short: 'CIC', long: 'Central Infrastructure Consultant' },
	{ short: 'CII', long: 'Critical Information Infrastructure' },
	{ short: 'CIM', long: 'Central Infrastructure Manager' },
	{ short: 'CIO', long: 'Chief Information Officer' },
	{ short: 'CIP', long: 'Continual Improvement Plan' },
	{ short: 'CISO', long: 'Chief Information Security Officer' },
	{ short: 'CIT', long: 'Central Indonesia Time' },
	{ short: 'CITPM', long: 'Certified IT Project Manager Programme' },
	{ short: 'CITREP', long: 'Critical Infocomm Technology Resource Programme' },
	{ short: 'CIU', long: 'Counselling and Intervention Unit' },
	{ short: 'CLC', long: 'Centre for Liveable Cities' },
	{ short: 'CLG', long: 'Clusters Group' },
	{ short: 'CLST', long: 'Chile Summer Time' },
	{ short: 'CLT', long: 'Chile Standard Time' },
	{ short: 'CMG', long: 'Communications & Marketing Group, GovTech' },
	{ short: 'CMI', long: 'Capital Markets Intermediaries' },
	{ short: 'CMS', long: 'Content Management System' },
	{ short: 'CNA', long: 'Cloud Native Architecture' },
	{ short: 'CNB', long: 'Central Narcotics Bureau' },
	{ short: 'CO', long: 'Countersigning Officer' },
	{ short: 'COC', long: 'Certificate Of Completion' },
	{ short: 'COC', long: 'Code Of Conduct' },
	{ short: 'CODEX', long: 'Core Operations Development Environment and eXchange' },
	{ short: 'COE', long: 'Certificate Of Entitlement' },
	{ short: 'COG', long: 'Center Of Government' },
	{ short: 'COISCM', long: 'Centre Of Innovation for Supply Chain Management' },
	{ short: 'COM', long: 'CIO Ops Meeting' },
	{ short: 'CONOPS', long: 'Concept of Operations' },
	{ short: 'COP', long: 'Community Of Practices' },
	{ short: 'COPS', long: 'Committee Of Permanent Secretaries' },
	{ short: 'COR', long: 'Charge Out Rates' },
	{ short: 'COS', long: 'Committee Of Supply' },
	{ short: 'COST', long: 'Colombia Summer Time' },
	{ short: 'COT', long: 'Colombia Time' },
	{ short: 'COV', long: 'Cash Over Valuation' },
	{ short: 'CP2M', long: 'Centre for Public Project Management' },
	{ short: 'CPAD', long: 'Corporate Planning & Administration Department' },
	{ short: 'CPB', long: 'Corporate Performance Bonus' },
	{ short: 'CPC', long: 'Cost Per Click' },
	{ short: 'CPDD', long: 'Curriculum Planning and Development Division' },
	{ short: 'CPE', long: 'Council For Private Education' },
	{ short: 'CPF', long: 'Central Provident Fund' },
	{ short: 'CPFB', long: 'Central Provident Fund Board' },
	{ short: 'CPIB', long: 'Corrupt Practices Investigation Bureau' },
	{ short: 'CPM', long: 'Cost Per Thousand' },
	{ short: 'CPS', long: 'Child Protective Service' },
	{ short: 'CPWG', long: 'CLP Procurement Working Group' },
	{ short: 'CRA', long: 'Casino Regulatory Authority of Singapore' },
	{ short: 'CRD', long: 'Competition & Resilience Development' },
	{ short: 'CRM', long: 'Customer Relationship Management' },
	{ short: 'CRO', long: 'Chief Records Officer' },
	{ short: 'CRO', long: 'Chief Risk Officer' },
	{ short: 'CRS', long: 'Call Report System' },
	{ short: 'CS', long: 'Corporate Services' },
	{ short: 'CS Card', long: 'Civil Service Card' },
	{ short: 'CSA', long: 'Cyber Security Agency of Singapore' },
	{ short: 'CSC', long: 'Civil Service College' },
	{ short: 'CSCP', long: 'Civil Service Computerisation Plan' },
	{ short: 'CSDM', long: 'Complex Systems Design & Management' },
	{ short: 'CSG', long: 'Govtech - Cyber Security Group' },
	{ short: 'CSIRT', long: 'Computer Security Incident Response Teams' },
	{ short: 'CSP', long: 'Career Support Programme' },
	{ short: 'CSP', long: 'Cloud Service Provider' },
	{ short: 'CSP', long: 'Common Service Provider' },
	{ short: 'CSS', long: 'Customer Satisfaction Survey' },
	{ short: 'CST', long: 'Central Standard Time USA' },
	{ short: 'CST', long: 'China Standard Time' },
	{ short: 'CTA', long: 'Call To Action' },
	{ short: 'CTE', long: 'Central Expressway' },
	{ short: 'CTMO', long: 'Clusters and Technology Management Office' },
	{ short: 'CTO', long: 'Chief Technology Officer' },
	{ short: 'CTR', long: 'Click Through Rate' },
	{ short: 'CTS', long: 'Central Technical Services' },
	{ short: 'CUSTOMS', long: 'Singapore Customs' },
	{ short: 'CV', long: 'Contract Variation' },
	{ short: 'CWC', long: 'Cyber Watch Centre' },
	{ short: 'CWP', long: 'Cut Waste Panel' },
	{ short: 'CWP', long: 'Content Web Platform' },
	{ short: 'CentEx', long: 'Centre of Excellence' },
	{ short: 'Centexes', long: 'Centres of Excellence' },
	{ short: 'CoL', long: 'Collaborative Learning' },
	{ short: 'D&D', long: 'Dinner & Dance' },
	{ short: 'D3', long: 'Digital Design and Development' },
	{ short: 'DA', long: 'Demand Aggregation' },
	{ short: 'DAPG', long: 'Data Analytics Practice Group' },
	{ short: 'DC', long: 'Developing Contributor' },
	{ short: 'DC', long: 'Direct Contracting' },
	{ short: 'DC', long: 'Development Charge' },
	{ short: 'DC', long: 'Distribution Centre' },
	{ short: 'DCE', long: 'Deputy CEO' },
	{ short: 'DCI', long: 'Digital Cinema Initiatives' },
	{ short: 'DCO', long: 'Defence Cyber Organization, MINDEF' },
	{ short: 'DCS', long: 'Document Collaboration Service' },
	{ short: 'DDUT', long: "Dumont d'Urville Time" },
	{ short: 'DE', long: 'Digital Economy' },
	{ short: 'DEF', long: 'Digital Economy Framework' },
	{ short: 'DES', long: 'Data Encryption Standard' },
	{ short: 'DESSA', long: 'Digital Economy Smart Services Architecture' },
	{ short: 'DEX', long: 'Samsung Desktop Experience' },
	{ short: 'DFMA', long: 'Design for Manufacturing & Assembly' },
	{ short: 'DFS', long: 'Domain, Functional, Specialist' },
	{ short: 'DGB', long: 'Digital Government Blueprint' },
	{ short: 'DGE', long: 'Director-General Education' },
	{ short: 'DH', long: 'Department Head' },
	{ short: 'DIC', long: 'Deputy In Charge' },
	{ short: 'DIC', long: 'DSTA Integrated Complex' },
	{ short: 'DISC', long: 'A Personality Type Analysis used by HR' },
	{ short: 'DISG', long: 'Digital Industry Singapore' },
	{ short: 'DLP', long: 'Digital Learning Platform' },
	{ short: 'DLT', long: 'Distributed Ledger Technology' },
	{ short: 'DM', long: 'Directors Meeting' },
	{ short: 'DMP', long: 'Data Management Platform' },
	{ short: 'DOS', long: 'Department Of Statistics' },
	{ short: 'DPC', long: 'Development Planning Committee' },
	{ short: 'DPI', long: 'Deep Packet Inspection' },
	{ short: 'DR Plan', long: 'Disaster Recovery Plan' },
	{ short: 'DRB', long: 'Digital Readiness Blueprint' },
	{ short: 'DRD', long: 'Data and Resilience Department' },
	{ short: 'DRE', long: 'Daily-Rated Employee' },
	{ short: 'DRM', long: 'Data Reference Model' },
	{ short: 'DRMS', long: 'Digital Record Management System' },
	{ short: 'DRO', long: 'Division Records Officer' },
	{ short: 'DRUMS', long: 'Distortions, Rumours, Untruths, Misinformation, and Smears' },
	{ short: 'DS', long: 'Deputy Secretary' },
	{ short: 'DSA', long: 'Direct School Admission' },
	{ short: 'DSAI', long: 'Data Science and Artificial Intelligence' },
	{ short: 'DSAID', long: 'Data Science and Artificial Intelligence Department' },
	{ short: 'DSD', long: 'Designated Specialised Department' },
	{ short: 'DSG', long: 'Design Singapore Council' },
	{ short: 'DSL', long: 'Digital Services Lab' },
	{ short: 'DSLC', long: 'Digital Services Lab Cluster' },
	{ short: 'DSP', long: 'Deputy Superintendent of Police' },
	{ short: 'DSRC', long: 'Dedicated Short Range Communications' },
	{ short: 'DSS', long: 'Digital Service Standards' },
	{ short: 'DSS', long: 'Digital Service Standard' },
	{ short: 'DSTA', long: 'Defence Science and Technology Agency' },
	{ short: 'DT', long: 'Design Thinking' },
	{ short: 'DU', long: 'Dwelling Unit' },
	{ short: 'DWP', long: 'Digital Workplace' },
	{ short: 'DWPO', long: 'Digital Workplace Programme Office' },
	{ short: 'DWT', long: 'Digital Workplace Transformation' },
	{ short: 'EAP', long: 'Employment Adjustment Programme' },
	{ short: 'EASE', long: 'Enterprise ProActive Support Environment' },
	{ short: 'EAT', long: 'East Africa Time' },
	{ short: 'EC', long: 'Establishment Committee' },
	{ short: 'ECDA', long: 'Early Childhood Development Agency' },
	{ short: 'ECM', long: 'Emergency Planning & Crisis Management' },
	{ short: 'ECRM', long: 'Electronic Customer Relationship Management' },
	{ short: 'ECT', long: 'Eastern Caribbean Time' },
	{ short: 'ED', long: 'Economy Drive' },
	{ short: 'ED-ITPWC', long: 'Economy Drive- InfoComm Technology P Working Committee' },
	{ short: 'EDB', long: 'Economic Development Board' },
	{ short: 'EDG', long: 'Enterprise Development Grant' },
	{ short: 'EDP', long: 'Enterprise Data Platform' },
	{ short: 'EDT', long: 'Eastern Daylight Time' },
	{ short: 'EES', long: 'Employee Engagement Survey' },
	{ short: 'EES', long: 'Employee Self Service' },
	{ short: 'EET', long: 'Eastern European Time' },
	{ short: 'EFMA', long: 'Employment of Foreign Manpower Act' },
	{ short: 'EGT', long: 'Eastern Greenland Time' },
	{ short: 'EIP', long: 'Ethnic Integration Policy' },
	{ short: 'EIT', long: 'Eastern Indonesian Time' },
	{ short: 'EIU', long: 'Economist Intelligence Unit- research organization' },
	{ short: 'ELD', long: 'Elections Department Singapore' },
	{ short: 'EMA', long: 'Energy Market Authority' },
	{ short: 'EMS', long: 'Entrepass Management System' },
	{ short: 'EOD', long: 'End Of Day' },
	{ short: 'EOL', long: 'End Of Life' },
	{ short: 'EOM', long: 'Expenditure Of Manpower' },
	{ short: 'EP', long: 'Emergency Preparedness' },
	{ short: 'EP', long: 'Employment Pass' },
	{ short: 'EPC', long: 'E-payments Committee' },
	{ short: 'EPO', long: 'ePolicy Ochestrator' },
	{ short: 'EPOL', long: 'Employment Pass Online' },
	{ short: 'EPP', long: 'Endpoint Protection' },
	{ short: 'EPPU', long: 'Expenditure and Policies Procurement Unit, MOF' },
	{ short: 'EPS', long: 'Electronic Public Services' },
	{ short: 'EPV', long: 'Estimated Procurement Value' },
	{ short: 'ERC', long: 'Economic Review Committee' },
	{ short: 'ERP', long: 'Enterprise Resource Planning' },
	{ short: 'ERP', long: 'Electronic Road Pricing' },
	{ short: 'ESDP', long: 'Electronic Services Delivery Programme' },
	{ short: 'ESG', long: 'Enterprise Singapore' },
	{ short: 'ESG', long: 'Environmental, Social and Governance' },
	{ short: 'EST', long: 'Eastern Standard Time USA' },
	{ short: 'ESub', long: 'eSubmission' },
	{ short: 'ETA', long: 'Electronic Transaction Act' },
	{ short: 'ETA', long: 'Electronic Transactions Act' },
	{ short: 'ETD', long: 'Educational Technology Division' },
	{ short: 'ETMS', long: 'Enterprise Threat Management Service' },
	{ short: 'ETPL', long: 'Exploit Technologies Pte Ltd' },
	{ short: 'EUCD', long: 'End-user Computing Device' },
	{ short: 'EUSH', long: 'End User Self-Help Portal' },
	{ short: 'EVP', long: 'Employee Value Proposition' },
	{ short: 'EVS', long: 'Enterprise Voice Service' },
	{ short: 'EXCEL', long: 'Excellence Through Continuous Enterprise and Learning' },
	{ short: 'EXCO', long: 'Executive Committee' },
	{ short: 'F&B', long: 'Food & Beverage' },
	{ short: 'FAA', long: 'Financial Approving Authority' },
	{ short: 'FAQ', long: 'Frequently Asked Questions' },
	{ short: 'FBO', long: 'Facilities Based Operators' },
	{ short: 'FCC', long: 'Functional Competency Courses' },
	{ short: 'FCM', long: 'Finance Circular Minutes' },
	{ short: 'FEC', long: 'Future Economy Committee' },
	{ short: 'FEPO', long: 'For entertainment purpose only' },
	{ short: 'FFE', long: 'File and Folder Encryption' },
	{ short: 'FFLP', long: 'Friendly Faces, Lively Places Fund, HDB' },
	{ short: 'FGD', long: 'Focus Group Discussion' },
	{ short: 'FICA', long: 'Countering Foreign Interference' },
	{ short: 'FIN', long: 'Foreign Identification Number' },
	{ short: 'FIPG', long: 'Finance, Investment & Procurement Group' },
	{ short: 'FISH', long: 'EFficient RetrIeval of Shared Know-How' },
	{ short: 'FJT', long: 'Fiji Time' },
	{ short: 'FKST', long: 'Falkland Islands Summer Time' },
	{ short: 'FLE', long: 'Field Level Encryption' },
	{ short: 'FLEX', long: 'Flexible Benefits Program' },
	{ short: 'FNC', long: 'Finance Cluster' },
	{ short: 'FNT', long: 'Fernando de Noronha Time' },
	{ short: 'FNV', long: 'Fax and voice' },
	{ short: 'FOH', long: 'Friends of Our Heartlands' },
	{ short: 'FP1', long: 'Fusionopolis 1' },
	{ short: 'FPE', long: 'Format Preserving Encryption' },
	{ short: 'FRC', long: 'Fast Response Car' },
	{ short: 'FRS', long: 'File Registry System' },
	{ short: 'FSC', long: 'Full-time School Counsellor' },
	{ short: 'FTA', long: 'Free Trade Agreement' },
	{ short: 'FTNS', long: 'Full-Time National Service' },
	{ short: 'FWIW', long: "For what it's worth" },
	{ short: 'FY', long: 'Financial Year' },
	{ short: 'FYNA', long: 'For Your Necessary Action' },
	{ short: 'G2B', long: 'Government to Business' },
	{ short: 'GATS', long: 'General Agreement on Trade in Services' },
	{ short: 'GCC', long: 'Government Commercial Cloud' },
	{ short: 'GCDTO', long: 'Government Chief Digital Technology Officer' },
	{ short: 'GCHE', long: 'Government Compliant Hosting Environment' },
	{ short: 'GCP', long: 'Google Cloud Platform' },
	{ short: 'GCSO', long: 'Government Cyber Security Operations' },
	{ short: 'GDC', long: 'Government Data Centre' },
	{ short: 'GDO', long: 'Government Data Office, SNGDO' },
	{ short: 'GDPR', long: 'General Data Protection Regulation, European Union' },
	{ short: 'GDS', long: 'Government Data Strategy' },
	{ short: 'GDS', long: 'Government Digital Service' },
	{ short: 'GDSC', long: 'Government Data Steering Committee' },
	{ short: 'GDSG', long: 'Government Digital Services Group' },
	{ short: 'GEMS', long: 'Government Electronic Mail System' },
	{ short: 'GEN', long: 'Government Enterprise Network' },
	{ short: 'GET', long: 'Georgia Standard Time' },
	{ short: 'GFE', long: 'Government Furnished Equipment' },
	{ short: 'GFI', long: 'Government Furnished Information' },
	{ short: 'GFT', long: 'French Guiana Time' },
	{ short: 'GH', long: 'Group Head' },
	{ short: 'GIAS', long: 'Government Internet Access Service' },
	{ short: 'GICS', long: 'Government Infrastructure Cybersecurity Services' },
	{ short: 'GIG', long: 'Government Infrastructure Group, GovTech' },
	{ short: 'GIMI', long: 'Government Integrated Messaging Infrastructure' },
	{ short: 'GITD', long: 'Group IT Division' },
	{ short: 'GITD', long: 'Group IT Department' },
	{ short: 'GITSIR', long: 'Government IT Security Incident Response, GovTech' },
	{ short: 'GLCs', long: 'Government-linked Companies' },
	{ short: 'GLS', long: 'Grocery Logistics Singapore' },
	{ short: 'GLS', long: 'Government Land Sales' },
	{ short: 'GMNet', long: 'Government Managed Network' },
	{ short: 'GMT', long: 'Greenwich Mean Time' },
	{ short: 'GNA', long: 'Good Neighbour Award' },
	{ short: 'GNOC', long: 'Government Network Operations Centre' },
	{ short: 'GOA', long: 'Government Online Asset' },
	{ short: 'GPA', long: 'Government Procurement Agreement' },
	{ short: 'GPAA', long: 'Grants and Projects Approving Authority' },
	{ short: 'GPC', long: 'Government Parliamentary Committee' },
	{ short: 'GPC', long: 'Government Private Cloud' },
	{ short: 'GPE', long: 'Government Procurement Entities' },
	{ short: 'GPO', long: 'Group Policy' },
	{ short: 'GPP', long: 'E-Government Policies & Programmes' },
	{ short: 'GRL', long: 'Grass Roots Leaders' },
	{ short: 'GS', long: 'Government Systems' },
	{ short: 'GSIB', long: 'Government Standard Image Build' },
	{ short: 'GSOC', long: 'Government Security Operations Centre' },
	{ short: 'GSS', long: 'Government Security Services' },
	{ short: 'GSSO', long: 'Government Standard Software Package' },
	{ short: 'GST', long: 'Gulf Standard Time' },
	{ short: 'GST', long: 'Goods and Services Tax' },
	{ short: 'GTM', long: 'Google Tag Manager' },
	{ short: 'GUT', long: 'Gateway Utility Tier, AIAS' },
	{ short: 'GVG', long: 'Governance Group, GovTech' },
	{ short: 'GWS-X', long: 'Government Web Services Exchange' },
	{ short: 'GYT', long: 'Guyana Time' },
	{ short: 'Gcloud', long: 'Government Cloud' },
	{ short: 'GeBIZ', long: 'Government Electronic Business' },
	{ short: 'GovTech', long: 'Government Agency of Singapore' },
	{ short: 'Gssp', long: 'Government Security Service' },
	{ short: 'H1H2H3', long: 'Horizon 1/2/3' },
	{ short: 'HADR', long: 'High Availability Disaster Recovery' },
	{ short: 'HCS', long: 'Head Civil Service' },
	{ short: 'HDB', long: 'Housing & Development Board' },
	{ short: 'HITS', long: 'Hub for Internet and Intranet Services' },
	{ short: 'HKT', long: 'Hong Kong Time' },
	{ short: 'HMG', long: 'Housing Maintenance Group' },
	{ short: 'HOD', long: 'Head of Division' },
	{ short: 'HOD', long: 'Head of Department' },
	{ short: 'HPB', long: 'Health Promotion Board' },
	{ short: 'HRL', long: 'HR Leaders and Reps' },
	{ short: 'HRLM', long: 'Human Resource Leaders Meeting' },
	{ short: 'HRMS', long: 'Human Resource Management System' },
	{ short: 'HRP', long: 'HR & Payroll' },
	{ short: 'HRPS', long: 'HR & Payroll System' },
	{ short: 'HSA', long: 'Health Sciences Authority' },
	{ short: 'HST', long: 'HawaiiAleutian Standard Time' },
	{ short: 'HTA', long: 'Home Team Academy' },
	{ short: 'I2R', long: 'Institute for Infocomm Research' },
	{ short: 'IA', long: 'Internal Audit' },
	{ short: 'IAA', long: 'Internal Approving Authority' },
	{ short: 'IAAS', long: 'Account Application System' },
	{ short: 'IAP', long: 'Infocomm Advisory Panel' },
	{ short: 'IB', long: 'Initiation Budget' },
	{ short: 'IBBMM', long: 'Interactive Broadband Multimedia' },
	{ short: 'ICA', long: 'Immigration & Checkpoints Authority of Singapore' },
	{ short: 'ICM', long: 'Infocomm and Media' },
	{ short: 'ICO', long: 'Initial Coin Offering' },
	{ short: 'ICT', long: 'Indochina Time' },
	{ short: 'ICT', long: 'Information and Communications Technology' },
	{ short: 'ICT', long: 'Info Comm Technology' },
	{ short: 'ICT', long: 'Intra-Corporate Transferee' },
	{ short: 'ICT RPO', long: 'ICT Recovery Point Objective' },
	{ short: 'ICT RTO', long: 'ICT Recovery Time Objective' },
	{ short: 'ICYMI', long: 'In Case You Missed It' },
	{ short: 'IDG', long: 'InfoComm Discussion Group' },
	{ short: 'IDL', long: 'Interface Description Language' },
	{ short: 'IDMF', long: 'Integrated Data Management Framework' },
	{ short: 'IDP', long: 'Individual Development Plan' },
	{ short: 'IDS', long: 'Intrusion detection system' },
	{ short: 'IDT', long: 'Israel Daylight Time' },
	{ short: 'IE Singapore', long: 'International Enterprise Singapore' },
	{ short: 'IEM', long: 'Integrated Environment Modeller' },
	{ short: 'IEP', long: 'InfoComm Education Program' },
	{ short: 'IFH', long: 'InfoComm Hub' },
	{ short: 'IFS', long: 'IDA Industry Feedback Survey' },
	{ short: 'IHLs', long: 'Institutes of Higher Learning' },
	{ short: 'ILEs', long: 'Infocomm Local Enterprises' },
	{ short: 'IM', long: 'Instruction Manual' },
	{ short: 'IM1', long: 'Instruction Manual 1 on Financial Control' },
	{ short: 'IM2', long: 'Instruction Manual 2 on Human Resource Management' },
	{ short: 'IM3', long: 'Instruction Manual 3 on Procurement' },
	{ short: 'IM4', long: 'Instruction Manual 4 on Asset Management' },
	{ short: 'IM5', long: 'Instruction Manual 5 on Revenue Contracting' },
	{ short: 'IM6', long: 'Instruction Manual 6 on Office Administration' },
	{ short: 'IM7', long: 'Instruction Manual 7 on Public Communications and Quality Service' },
	{ short: 'IM8', long: 'Instruction Manual 8 on ICT Management' },
	{ short: 'IMC', long: 'Inter Ministerial Committee' },
	{ short: 'IMC', long: 'International Maritime Centre' },
	{ short: 'IMCS', long: 'Instant Messaging and Conferencing Service' },
	{ short: 'IMD', long: 'In Mall Distribution' },
	{ short: 'IMDA', long: 'Info-communications Media Development Authority' },
	{ short: 'IMO', long: 'In My Opinion' },
	{ short: 'IMP', long: 'Internal Market Place' },
	{ short: 'IOC', long: 'Initial Operational Capability' },
	{ short: 'IOC', long: 'Integrated Operations Centre' },
	{ short: 'IOC', long: 'Infrastructure Operations Command' },
	{ short: 'IP', long: 'Investigation Paper' },
	{ short: 'IP', long: 'Intellectual Property' },
	{ short: 'IPAM', long: 'Institute of Public Administration and Management' },
	{ short: 'IPB', long: 'Individual Performance Bonus' },
	{ short: 'IPI', long: 'Intellectual Property Intermediary' },
	{ short: 'IPOS', long: 'Intellectual Property Office Of Singapore' },
	{ short: 'IPRS', long: 'Purchase Requisition System' },
	{ short: 'IQA', long: 'Internal Quality Audit' },
	{ short: 'IQTs', long: 'Innovation & Quality Teams' },
	{ short: 'IRAS', long: 'Inland Revenue Authority Of Singapore' },
	{ short: 'IRDT', long: 'Iran Daylight Time' },
	{ short: 'IRST', long: 'Iran Standard Time' },
	{ short: 'ISEAS', long: 'Institute of Southeast Asian Studies' },
	{ short: 'ISM', long: 'Information Systems Manager' },
	{ short: 'ISMC', long: 'Information Systems Management Committee' },
	{ short: 'ISMP', long: 'Infocomm Security Masterplan' },
	{ short: 'ISP', long: 'Internet Service Providers' },
	{ short: 'ISS', long: 'Internet Surfing Separation' },
	{ short: 'IST', long: 'Israel Standard Time' },
	{ short: 'IST', long: 'Indian Standard Time' },
	{ short: 'ISTANA', long: "President's Office, Istana" },
	{ short: 'IT', long: 'Integration Tier' },
	{ short: 'ITE', long: 'Institute of Technical Education' },
	{ short: 'ITM', long: 'Infocomm Media Industry Transformation Map' },
	{ short: 'ITQ', long: 'Invitation to Quote' },
	{ short: 'ITR', long: 'Infocomm Technology Roadmap' },
	{ short: 'ITSC', long: 'Information Technology Standards Committee' },
	{ short: 'ITSM', long: 'IT Service Management' },
	{ short: 'ITT', long: 'Invitation to Tender' },
	{ short: 'IaaS', long: 'Infrastructure as a Service' },
	{ short: 'IoT', long: 'Internet of things' },
	{ short: 'JD', long: 'Job Description' },
	{ short: 'JOC', long: 'Joint Operations Command' },
	{ short: 'JOL', long: 'Joy of Learning' },
	{ short: 'JOS', long: 'Joint Operations Secretariat' },
	{ short: 'JPEG', long: 'Joint Photographic Experts Group' },
	{ short: 'JSON', long: 'JavaScript Object Notation' },
	{ short: 'JST', long: 'Japan Standard Time' },
	{ short: 'JTC', long: 'JTC Corporation' },
	{ short: 'KB', long: 'Knowledge Bank' },
	{ short: 'KEN', long: 'Knowledge Enterprise Network' },
	{ short: 'KIV', long: 'Keep In View' },
	{ short: 'KM', long: 'Knowledge Management' },
	{ short: 'KMEP', long: 'Knowledge Management Experimentation Programme' },
	{ short: 'KPI', long: 'Key Performance Index' },
	{ short: 'KPI', long: 'Key Performance Indicator' },
	{ short: 'KST', long: 'Korea Standard Time' },
	{ short: 'KYC', long: 'Know Your Customer' },
	{ short: 'LDA', long: 'Latent Dirichlet Allocation' },
	{ short: 'LDAP', long: 'Lightweight Directory Access Protocol' },
	{ short: 'LDAPS', long: 'Lightweight Directory Access Protocol Over Secure Socket Links' },
	{ short: 'LEDP', long: 'Local Enterprise Development Programme' },
	{ short: 'LEW', long: 'Licensed Electrical Worker' },
	{ short: 'LGTM', long: 'Looks Good To Me' },
	{ short: 'LHST', long: 'Lord Howe Standard Time' },
	{ short: 'LIDAR', long: 'Light Detecting and Ranging' },
	{ short: 'LINT', long: 'Line Islands Time' },
	{ short: 'LLE', long: 'Large Local Enterprise' },
	{ short: 'LLP', long: 'Learning for Life Programme' },
	{ short: 'LMS', long: 'Learning Management System' },
	{ short: 'LOA', long: 'Letter Of Approval' },
	{ short: 'LOA', long: 'Leave Of Absence' },
	{ short: 'LOA', long: 'Letter Of Award' },
	{ short: 'LPS', long: 'Large Panel Slab' },
	{ short: 'LRD', long: 'Learning Resource Directory' },
	{ short: 'LRS', long: 'Log Retrieval System' },
	{ short: 'LTA', long: 'Land Transport Authority' },
	{ short: 'LTEA', long: 'Land Transport Excellence Awards' },
	{ short: 'LTSS', long: 'Long Term Service Support' },
	{ short: 'LUP', long: 'Lift Upgrading Programme' },
	{ short: 'LX', long: 'Leadership eXchange' },
	{ short: 'MA', long: 'Matters Arising' },
	{ short: 'MAC', long: 'Market Adjustment Component' },
	{ short: 'MARK', long: 'MediA Relations Knowledge Management System' },
	{ short: 'MART', long: 'Marquesas Islands Time' },
	{ short: 'MAS', long: 'Monetary Authority of Singapore' },
	{ short: 'MAU', long: 'Monthly Active User' },
	{ short: 'MBC', long: 'Mapletree Business Center' },
	{ short: 'MBIM', long: 'Medical Benefits Identity Memo' },
	{ short: 'MC', long: 'Medical Certificate' },
	{ short: 'MC', long: 'Management Committee' },
	{ short: 'MCCY', long: 'Ministry Of Culture, Community And Youth' },
	{ short: 'MCF', long: 'My Careers Future' },
	{ short: 'MCG', long: 'Multi Company Group' },
	{ short: 'MCI', long: 'Ministry of Communications and Information' },
	{ short: 'MCIO', long: 'Microsoft Cloud Infrastructure and Operations' },
	{ short: 'MCISO', long: 'Ministry Chief Information Security Officer' },
	{ short: 'MCS', long: 'Mission-Critical Systems' },
	{ short: 'MDP', long: 'Minor Development Project' },
	{ short: 'MDV', long: 'Minor Development Vote' },
	{ short: 'MEST', long: 'Middle European Summer Time' },
	{ short: 'MEWR', long: 'Ministry of Environment and Water Resources' },
	{ short: 'MFA', long: 'Multi Factor Authentication' },
	{ short: 'MFA', long: 'Ministry of Foreign Affairs' },
	{ short: 'MFDP', long: 'Ministry Family Digitalisation Plan' },
	{ short: 'MHA', long: 'Ministry of Home Affairs' },
	{ short: 'MHI', long: 'Managed Hosting Infrastructure' },
	{ short: 'MI', long: 'Messaging Infrastructure' },
	{ short: 'MI', long: 'Merit Increment' },
	{ short: 'MIC', long: 'Manager In Charge' },
	{ short: 'MICE', long: 'Meetings, Incentives, Conventions and Exhibitions' },
	{ short: 'MIN', long: 'Minister' },
	{ short: 'MINDEF', long: 'Ministry of Defence' },
	{ short: 'MINLAW', long: 'Ministry of Law' },
	{ short: 'MLC', long: 'Micro-Learning Course' },
	{ short: 'MM', long: 'Middle Management' },
	{ short: 'MMBA', long: 'Ministry Medical Benefits Administrator' },
	{ short: 'MMF', long: 'Manpower Management Framework' },
	{ short: 'MMT', long: 'Myanmar Standard Time' },
	{ short: 'MND', long: 'Ministry of National Development' },
	{ short: 'MOCC', long: 'Monitoring and Operations Command Centre' },
	{ short: 'MOE', long: 'Ministry Of Education' },
	{ short: 'MOF', long: 'Ministry Of Finance' },
	{ short: 'MOH', long: 'Ministry Of Health' },
	{ short: 'MOI', long: 'Memorandum Of Intent' },
	{ short: 'MOL', long: 'Moments Of Life' },
	{ short: 'MOM', long: 'Ministry Of Manpower' },
	{ short: 'MOS', long: 'Minister Of State' },
	{ short: 'MOT', long: 'Ministry Of Transport' },
	{ short: 'MOU', long: 'Memorandum Of Understanding' },
	{ short: 'MP', long: 'Member of Parliament' },
	{ short: 'MPA', long: 'Maritime And Port Authority Of Singapore' },
	{ short: 'MPDA', long: 'Minimum Pension Drawing Age' },
	{ short: 'MPLS', long: 'Multi Protocol Label Switching' },
	{ short: 'MPS', long: 'Managed Print Services' },
	{ short: 'MRO', long: 'Maintenance Repair Overhaul' },
	{ short: 'MRSS', long: 'Media RSS' },
	{ short: 'MS', long: 'Mail Service' },
	{ short: 'MSF', long: 'Multi Source Feedback' },
	{ short: 'MSF', long: 'Ministry Of Social And Family Development' },
	{ short: 'MSK', long: 'Moscow Time' },
	{ short: 'MSL', long: 'MediShield Life' },
	{ short: 'MSM', long: 'Ministerial Staff Meeting' },
	{ short: 'MSO', long: 'Medisave-cum-Subsidised Outpatient' },
	{ short: 'MSO', long: 'Management Support Officer' },
	{ short: 'MSP', long: 'Minimum Service Period' },
	{ short: 'MSS', long: 'Management Support Scheme' },
	{ short: 'MST', long: 'Malaysia Standard Time' },
	{ short: 'MST', long: 'Mountain Standard Time USA' },
	{ short: 'MTF', long: 'Multi-Ministry Taskforce' },
	{ short: 'MTI', long: 'Ministry of Trade and Industry' },
	{ short: 'MUIS', long: 'Majlis Ugama Islam Singapura' },
	{ short: 'MUT', long: 'Mauritius Time' },
	{ short: 'MVP', long: 'Minimum Viable Product' },
	{ short: 'MXOs', long: 'Management Executives' },
	{ short: 'MXS', long: 'Management Executive Scheme' },
	{ short: 'MaaS', long: 'Mobility as a Service' },
	{ short: 'MoP', long: 'Member of Public' },
	{ short: 'NAC', long: 'National Arts Council' },
	{ short: 'NAC', long: 'Network Access Control' },
	{ short: 'NAF', long: 'National Authentication Framework' },
	{ short: 'NAI', long: 'National Authentication Infrastructure' },
	{ short: 'NAS', long: 'National Archives of Singapore' },
	{ short: 'NBN', long: 'National Broadband Network' },
	{ short: 'NCB', long: 'National Computer Board' },
	{ short: 'NCIRC', long: 'National Cybersecurity Incident Response Centre' },
	{ short: 'NCMP', long: 'Non-Constituency Member of Parliament' },
	{ short: 'NCSC', long: 'National Cable Standards Committee' },
	{ short: 'NCSS', long: 'National Council Of Social Service' },
	{ short: 'NDA', long: 'Non Disclosure Agreement' },
	{ short: 'NDA', long: 'National Day Award' },
	{ short: 'NDA', long: 'Non-Disclosure Agreement' },
	{ short: 'NDI', long: 'National Digital Identity' },
	{ short: 'NDP', long: 'National Day Parade' },
	{ short: 'NDS', long: 'National Data Strategy' },
	{ short: 'NDT', long: 'Newfoundland Daylight Time' },
	{ short: 'NEA', long: 'National Environment Agency' },
	{ short: 'NECTAR', long: 'Next-Generation Container Architecture' },
	{ short: 'NEV', long: 'Net Economic Value' },
	{ short: 'NFS', long: 'New Financial System' },
	{ short: 'NGC', long: 'NVIDIA GPU Cloud' },
	{ short: 'NGNII', long: 'Next Generation National Infocomm Infrastructure' },
	{ short: 'NGPP2', long: 'National Grid Pilot Platform 2' },
	{ short: 'NGW LAN', long: 'Next Generation Wireless Local Area Network' },
	{ short: 'NHB', long: 'National Heritage Board' },
	{ short: 'NHP', long: 'National Healthy Population' },
	{ short: 'NICC', long: 'National Infocomm Competency Centre' },
	{ short: 'NII', long: 'National Infocomm Infrastructure' },
	{ short: 'NIS', long: 'National Infocomm Scholarship' },
	{ short: 'NIST', long: 'National Institute of Standards and Technology' },
	{ short: 'NITLP', long: 'National IT Literacy Programme' },
	{ short: 'NLB', long: 'National Library Board' },
	{ short: 'NLP', long: 'Natural-language processing' },
	{ short: 'NMP', long: 'Nominated Member of Parliament' },
	{ short: 'NOM', long: 'Notice Of Meeting' },
	{ short: 'NP', long: 'Ngee Ann Polytechnic' },
	{ short: 'NPARKS', long: 'National Parks Board' },
	{ short: 'NPL', long: 'No-Pay Leave' },
	{ short: 'NPPK', long: 'New Phoenix Park' },
	{ short: 'NPT', long: 'Nepal Time' },
	{ short: 'NParks', long: 'National Park Board' },
	{ short: 'NRF', long: 'National Research Foundation' },
	{ short: 'NRFF', long: 'New Rail Financing Framework' },
	{ short: 'NRI', long: 'Networked Readiness Index' },
	{ short: 'NRIC', long: 'National Registration Identity Card' },
	{ short: 'NRP', long: 'Neighbourhood Renewal Programme' },
	{ short: 'NSC', long: 'National Speech Corpus' },
	{ short: 'NSC', long: 'North-South Corridor' },
	{ short: 'NSCS', long: 'National Security Coordination Secretariat' },
	{ short: 'NSEWL', long: 'North-South and East-West Lines' },
	{ short: 'NST', long: 'Newfoundland Standard Time' },
	{ short: 'NTC', long: 'National Translation Committee' },
	{ short: 'NTU', long: 'Nanyang Technological University' },
	{ short: 'NUHS', long: 'National University Health System' },
	{ short: 'NYC', long: 'National Youth Council of Singapore' },
	{ short: 'NYP', long: 'Nanyang Polytechnic' },
	{ short: 'NZDT', long: 'New Zealand Daylight Time' },
	{ short: 'NZST', long: 'New Zealand Standard Time' },
	{ short: 'NcTMC', long: 'National Cybersecurity Threat Monitoring Center' },
	{ short: 'NoSQL', long: 'Next Order Structed Query Language' },
	{ short: 'OBLS', long: 'Online Business Licensing Services' },
	{ short: 'OBS', long: 'Outward Bound Singapore' },
	{ short: 'OCR', long: 'Optical Character Recognition' },
	{ short: 'OCS', long: 'Organisation Climate Survey' },
	{ short: 'OD', long: 'Organization Development' },
	{ short: 'ODC', long: 'Organisation Development Committee' },
	{ short: 'ODIN', long: 'Organisational Diagnostic and Intelligence Network' },
	{ short: 'ODP', long: 'Open Digital Platform' },
	{ short: 'ODP', long: 'Overseas Development Programme' },
	{ short: 'OECD', long: 'Organisation for Economic Development and Co-operation' },
	{ short: 'OED', long: 'Organisational Excellence Department' },
	{ short: 'OED', long: 'Office Equipment' },
	{ short: 'OEM', long: 'Original Equipment Manufacturer' },
	{ short: 'OFWAS', long: 'Online Foreign Worker Address Service' },
	{ short: 'OGP', long: 'Open Government Product' },
	{ short: 'OIC', long: 'Officer-in-charge' },
	{ short: 'OM', long: 'Orientation Module' },
	{ short: 'OMA', long: 'Oracle Master Agreement' },
	{ short: 'OOB', long: 'Out Of Brand' },
	{ short: 'OOE', long: 'Other Operating Expenses' },
	{ short: 'OOM', long: 'Orders Of magnitude' },
	{ short: 'OOM', long: 'Out Of memory' },
	{ short: 'OOO', long: 'Out Of Office' },
	{ short: 'OPA', long: 'Oracle Policy Automation' },
	{ short: 'OPEX', long: 'Operational Expenditure' },
	{ short: 'OPS', long: 'Operations' },
	{ short: 'ORBAT', long: 'Order of Battle' },
	{ short: 'OS', long: 'OneService MSO' },
	{ short: 'OSA', long: 'Official Secret Act' },
	{ short: 'OSPO', long: 'Our Singapore Programme Office' },
	{ short: 'OSS', long: 'Operational Support Scheme' },
	{ short: 'OTP', long: 'One-time password' },
	{ short: 'OnePS WP', long: 'One Public Service WorkPlace' },
	{ short: 'P2P', long: 'Point-to-point' },
	{ short: 'PA', long: 'Peoples Association' },
	{ short: 'PA', long: 'Personal Assistant' },
	{ short: 'PAAS', long: 'Platform As A Service' },
	{ short: 'PARL', long: 'Parliament Of Singapore' },
	{ short: 'PARL Sec', long: 'Parliamentary secretary' },
	{ short: 'PATH', long: 'Pilot And Trial Hotspots' },
	{ short: 'PB', long: 'Performance Bonus' },
	{ short: 'PB', long: 'Personnel Board' },
	{ short: 'PBU', long: 'Prefabricated Bathroom Units' },
	{ short: 'PC', long: 'Personal Computer)' },
	{ short: 'PCA', long: 'Project Collaboration Agreement' },
	{ short: 'PCBT', long: 'PC Bulk Tender' },
	{ short: 'PCF', long: 'Position Clarification Form' },
	{ short: 'PCP', long: 'Professional Certification Programme' },
	{ short: 'PD', long: 'People Development' },
	{ short: 'PDA', long: 'Personal Digital Assistant' },
	{ short: 'PDD', long: 'Punggol Digital District' },
	{ short: 'PDF', long: 'Portable Document Format' },
	{ short: 'PDPA', long: 'Personal Data Protection Act' },
	{ short: 'PDS', long: 'People Developer Standards' },
	{ short: 'PEA', long: 'Performance Enhancement Activities' },
	{ short: 'PEA', long: 'Parlimentary Elections Act' },
	{ short: 'PEAP', long: 'Performance Enhancement Action Plan' },
	{ short: 'PERKS', long: 'Personal EnRichment Kit for Staff' },
	{ short: 'PET', long: 'Peru Time' },
	{ short: 'PG', long: 'Practice Group' },
	{ short: 'PG', long: 'Policy Group' },
	{ short: 'PGT', long: 'Papua New Guinea Time' },
	{ short: 'PHOT', long: 'Phoenix Island Time' },
	{ short: 'PI', long: 'Promotion Increment' },
	{ short: 'PIC', long: 'Person in-charge' },
	{ short: 'PII', long: 'Personally Identifiable Information' },
	{ short: 'PIP', long: 'Performance Improvement Plan' },
	{ short: 'PIP', long: 'PSD Internal Posting' },
	{ short: 'PIR', long: 'Post Implementation Review' },
	{ short: 'PIXEL', long: 'Productivity and Innovation eXperienced via EmaiL' },
	{ short: 'PKI', long: 'Public Key Infrastructure' },
	{ short: 'PKT', long: 'Pakistan Standard Time' },
	{ short: 'PM', long: 'Project Manager' },
	{ short: 'PM2S', long: 'People Matters Management System' },
	{ short: 'PMD', long: 'Personal Mobility Device' },
	{ short: 'PME', long: 'Professionals, Managers and Executives' },
	{ short: 'PMET', long: 'Professionals, Managers, Executives, and Technicians' },
	{ short: 'PMO', long: "Prime Minister's Office" },
	{ short: 'PMP', long: 'Project Management Plan' },
	{ short: 'PMP', long: 'Project Management Professional' },
	{ short: 'PMP', long: 'People Management Plan' },
	{ short: 'PMS', long: 'Performance Management System' },
	{ short: 'PO', long: 'Project Officer' },
	{ short: 'PO', long: 'Purchase Order' },
	{ short: 'POC', long: 'Point Of contact' },
	{ short: 'POC', long: 'Proof Of Concept' },
	{ short: 'POD', long: 'Proof Of Delivery' },
	{ short: 'PODH', long: 'Public Officer Data Hub' },
	{ short: 'POFMA', long: 'Protection from Online Falsehoods and Manipulation Act' },
	{ short: 'POG', long: 'People and Organisation Group' },
	{ short: 'POGIS', long: 'Public Officers Group Insurance Scheme' },
	{ short: 'POH', long: 'Political Office Holder' },
	{ short: 'POI', long: 'People Of Interest' },
	{ short: 'PORTS', long: 'Prisons Operations and Rehabilitation System' },
	{ short: 'POS', long: 'Point Of Sale' },
	{ short: 'POWER', long: 'Public Officers Working to Eliminate Red-Tape' },
	{ short: 'PP', long: 'Protection Profile' },
	{ short: 'PPC', long: 'Public Policy Challenge' },
	{ short: 'PPC', long: 'Pay Per Click' },
	{ short: 'PPCR', long: 'Pre & Post Course Review Form' },
	{ short: 'PPRF', long: 'Performance Planning and Review Form' },
	{ short: 'PPVC', long: 'Prefabricated Prefinished Volumetric Construction' },
	{ short: 'PQA', long: 'Planning & Quality Assurance' },
	{ short: 'PR', long: 'Purchase Requisition' },
	{ short: 'PR', long: 'Purchase Request' },
	{ short: 'PRIMME', long: 'Performance Recognition Incentive to Manage and Motivate Excellence' },
	{ short: 'PRIS', long: 'Plastics and Rubber Institute of Singapore' },
	{ short: 'PRP', long: 'Performance Review Process' },
	{ short: 'PS', long: 'Permanent Secretary' },
	{ short: 'PS21', long: 'Public Service for the 21st Century' },
	{ short: 'PSC', long: 'Public Service Commission' },
	{ short: 'PSC Gateway', long: 'PSC Gateway System' },
	{ short: 'PSD', long: 'Public Service Division' },
	{ short: 'PSDSRC', long: 'Public Sector Data Security Review Committee' },
	{ short: 'PSIC', long: 'Public Service Innovation Challenge' },
	{ short: 'PSIF', long: 'Public Sector InfoComm Forum' },
	{ short: 'PSIP', long: 'Public Service Induction Programme' },
	{ short: 'PSIRC', long: 'Public Sector ICT Review Committee' },
	{ short: 'PSIRC', long: 'People Sector Infocomm Resource Centre' },
	{ short: 'PSIS', long: 'Public Sector Infocomm Seminar' },
	{ short: 'PSISC', long: 'Public Sector InfoComm Steering Committee' },
	{ short: 'PSL', long: 'Public Service Leadership' },
	{ short: 'PSLP', long: 'Public Service Leadership Programme' },
	{ short: 'PSM', long: 'Premium Services Manager' },
	{ short: 'PSMP', long: 'PSC Scholars Mid-Course Programme' },
	{ short: 'PSO', long: 'People Sector Organisation' },
	{ short: 'PSST', long: 'Public Service Survey Tool' },
	{ short: 'PST', long: 'Public Service Transformation' },
	{ short: 'PST', long: 'Philippine Standard Time' },
	{ short: 'PST', long: 'Public Sector Transformation' },
	{ short: 'PST', long: 'Pacific Standard Time USA' },
	{ short: 'PSW', long: 'Public Service Week' },
	{ short: 'PSi', long: 'Public Sector InfoComm' },
	{ short: 'PT', long: 'Penetration Test' },
	{ short: 'PTC', long: 'Public Transport Council' },
	{ short: 'PUB', long: 'PUB, The National Water Agency' },
	{ short: 'PYST', long: 'Paraguay Summer Time' },
	{ short: 'PYT', long: 'Paraguay Time[8]' },
	{ short: 'PaC@Gov', long: 'Pay and Claims at Government' },
	{ short: 'PaaS', long: 'Platform as a Service' },
	{ short: 'PdM', long: 'Product Manager' },
	{ short: 'PenTest', long: 'Penetration Testing' },
	{ short: 'PgM', long: 'Programme Manager' },
	{ short: 'PrEA', long: 'Presidential Elections Act' },
	{ short: 'QA', long: 'Quality Audit' },
	{ short: 'QAA', long: 'Quotation Approving Authority' },
	{ short: 'QM', long: 'Quality Management' },
	{ short: 'QMS', long: 'Quality Management System' },
	{ short: 'QSM', long: 'Quality Service Management' },
	{ short: 'QSM', long: 'Quality Service Manager' },
	{ short: 'QSMO', long: 'Quality Service Manager Office' },
	{ short: 'QoS', long: 'Quality of Service' },
	{ short: 'R&P', long: 'Ranking and Promotion' },
	{ short: 'RACI', long: 'Responsible, Accountable, Consulted, Informed' },
	{ short: 'RBS', long: 'Resource Booking System' },
	{ short: 'RBS', long: 'Room Booking System' },
	{ short: 'RCA', long: 'Research Collaboration Agreement' },
	{ short: 'RDD', long: 'Resume Driven Development' },
	{ short: 'RE', long: 'Register of Electors' },
	{ short: 'RF', long: 'Reinvestment Fund' },
	{ short: 'RFC', long: 'Request For Concept' },
	{ short: 'RFI', long: 'Request for information' },
	{ short: 'RFP', long: 'Request For Proposal' },
	{ short: 'RFQ', long: 'Request For Quotation' },
	{ short: 'RIO', long: 'Reference Interconnection Offer' },
	{ short: 'RM', long: 'Risk Management' },
	{ short: 'RM', long: 'Resource Management' },
	{ short: 'RMF', long: 'Robotics Middleware Framework' },
	{ short: 'RMF', long: 'Risk Management Framework' },
	{ short: 'RMM', long: 'Risk Management Methodology' },
	{ short: 'RMT', long: 'Records Management Team' },
	{ short: 'RO', long: 'Reporting Officer' },
	{ short: 'ROH', long: 'Remaking Our Heartland programme' },
	{ short: 'ROI', long: 'Return on Investment' },
	{ short: 'ROM', long: 'Registry Of Marriages' },
	{ short: 'ROS', long: 'Robotics Operating System' },
	{ short: 'ROTT', long: 'Rothera Research Station Time' },
	{ short: 'RP', long: 'Republic Polytechnic' },
	{ short: 'RPA', long: 'Robotic Process Automation' },
	{ short: 'RPCA', long: 'Robust Principal Component Analysis' },
	{ short: 'RPG', long: 'Research & Planning Group' },
	{ short: 'RPO', long: 'Recovery Point Objective' },
	{ short: 'RSAF', long: 'Republic of Singapore Airforce' },
	{ short: 'RSN', long: 'Republic of Singapore Navy' },
	{ short: 'RSS', long: 'Retirement Sum Scheme' },
	{ short: 'RSS', long: 'Rich Site Summary' },
	{ short: 'RSS', long: 'Really Simple Syndication' },
	{ short: 'RTI', long: 'Real-Time Innovations' },
	{ short: 'RTO', long: 'Recovery Time Objective' },
	{ short: 'SA', long: 'Solution Architect' },
	{ short: 'SAARC', long: 'South Asian Association for Regional Cooperation' },
	{ short: 'SAC', long: 'Singapore Accountancy Commission' },
	{ short: 'SAF', long: 'Singapore Armed Forces' },
	{ short: 'SAMi', long: 'Salary Administration Interactive' },
	{ short: 'SAP', long: 'Systems,Applications and Products: German enterprise software company' },
	{ short: 'SAR', long: 'Staff Appraisal Report' },
	{ short: 'SAST', long: 'South African Standard Time' },
	{ short: 'SBB', long: 'Subject Based Banding' },
	{ short: 'SBD', long: 'Security By Design' },
	{ short: 'SBO', long: 'Services Based Operations' },
	{ short: 'SBRM', long: 'PS-Level Strategic Budget Review Meetings' },
	{ short: 'SBRM', long: 'Strategic Budget Review Meeting' },
	{ short: 'SC', long: 'Strategic Communications' },
	{ short: 'SCB', long: 'Science Centre Board' },
	{ short: 'SCDF', long: 'Singapore Civil Defence Force' },
	{ short: 'SCE', long: 'Singapore Cooperation Enterprise' },
	{ short: 'SCM', long: 'SNDGO Circular Minutes' },
	{ short: 'SCORE', long: 'Singapore Corporation Of Rehabilitative Enterprises' },
	{ short: 'SCS', long: 'Singapore Computer System' },
	{ short: 'SCS', long: 'Singapore Computer Society' },
	{ short: 'SCS', long: 'Security Compliance Service' },
	{ short: 'SCT', long: 'Seychelles Time' },
	{ short: 'SD', long: 'Senior Director' },
	{ short: 'SDC', long: 'Singapore Dental Council' },
	{ short: 'SDF', long: 'Skills Development Fund' },
	{ short: 'SDL', long: 'skills development levy' },
	{ short: 'SDL', long: 'Self-Directed Learning' },
	{ short: 'SDLC', long: 'Software Development Life Cycle' },
	{ short: 'SDRP', long: 'Singapore Domain Name Dispute Resolution Policy' },
	{ short: 'SE', long: 'SafeEntry' },
	{ short: 'SE2', long: 'Secure Email 2' },
	{ short: 'SEA', long: 'South East Asia' },
	{ short: 'SEAB', long: 'Singapore Examinations And Assessment Board' },
	{ short: 'SEC', long: 'Secondment' },
	{ short: 'SEMPO', long: 'Security and Emergency Planning Office' },
	{ short: 'SENTOSA', long: 'Sentosa Development Corporation' },
	{ short: 'SEO', long: 'Search Engine Optimisation' },
	{ short: 'SERS', long: 'Selective En-bloc Redevelopment Scheme' },
	{ short: 'SEV 1', long: 'Severity 1' },
	{ short: 'SFA', long: 'Singapore Food Agency' },
	{ short: 'SFDC', long: 'Social and Family Development Cluster' },
	{ short: 'SFO', long: 'Strategic Futures Office' },
	{ short: 'SFTP', long: 'Secured File Transfer Protocol' },
	{ short: 'SG DRM', long: 'Singapore Government Data Reference Model' },
	{ short: 'SG SPACE', long: 'Singapore Geospatial Collaborative Environment' },
	{ short: 'SG TRM', long: 'Singapore Government - Technology Reference Model' },
	{ short: 'SG-EPP', long: 'Endpoint Protection Service' },
	{ short: 'SG-IMCS', long: 'SG-Mail Instant Messaging & Conferencing Service' },
	{ short: 'SG-SDS', long: 'Software Distribution Service' },
	{ short: 'SG-TRM', long: 'Singapore Government Technology Reference Modal' },
	{ short: 'SGDI', long: 'Singapore Government Directory' },
	{ short: 'SGEMS', long: 'Singapore Government Electronic Messaging System' },
	{ short: 'SGMS', long: 'Singapore Government MetaData Standards' },
	{ short: 'SGNET', long: 'Singapore Government Network' },
	{ short: 'SGO', long: 'Silver Generation Office' },
	{ short: 'SGQR', long: 'Singapore Quick Response Code' },
	{ short: 'SGTM', long: 'Sounds Good To Me' },
	{ short: 'SGTS', long: 'Singapore Government Technology Stack' },
	{ short: 'SHA', long: 'Secure Hash Algorithm' },
	{ short: 'SHINE', long: 'Service Wide Hosting Environment' },
	{ short: 'SHIP', long: 'Secure Hybrid Integrated Pipeline' },
	{ short: 'SI', long: 'Salary Increment' },
	{ short: 'SI', long: 'System Integrator' },
	{ short: 'SIC', long: 'Staff In Confidence' },
	{ short: 'SIEM', long: 'Security Information and Event Management' },
	{ short: 'SIEVE', long: 'Secure Internetworking Environment using Virtual Private Network' },
	{ short: 'SIGs', long: 'Special Interest Groups' },
	{ short: 'SII', long: 'Significant Information Infrastructure' },
	{ short: 'SINDA', long: 'Singapore Indian Development Association' },
	{ short: 'SINGSTAT', long: 'Singapore Department of Statistics' },
	{ short: 'SIOT', long: 'Sensors & IoT' },
	{ short: 'SIRM', long: 'Security Incident Response Manager' },
	{ short: 'SIRO', long: 'Security Incident Response Officer' },
	{ short: 'SIT', long: 'System Integration Testing' },
	{ short: 'SITF', long: 'Singapore Iinformation Technology Federation' },
	{ short: 'SITREP', long: 'Situation Report' },
	{ short: 'SIU', long: 'Service Improvement Unit' },
	{ short: 'SKU', long: 'Stock Keeping Unit' },
	{ short: 'SLA', long: 'Singapore Land Authority' },
	{ short: 'SLA', long: 'Service Level Agreement' },
	{ short: 'SLF', long: 'Senior Leadership Forum' },
	{ short: 'SLF', long: 'Singapore Labour Foundation' },
	{ short: 'SLM', long: 'Senior Level Management' },
	{ short: 'SLM', long: 'Senior Leadership Meeting' },
	{ short: 'SLS', long: 'Student Learning Space' },
	{ short: 'SLSPS', long: 'Student Learning Space Pedagogical Scaffold' },
	{ short: 'SLST', long: 'Sri Lanka Standard Time' },
	{ short: 'SMC', long: 'Singapore Medical Council' },
	{ short: 'SMCCI', long: 'Singapore Malay Chamber of Commerce & Industry' },
	{ short: 'SME', long: 'Small and Medium Enterprises' },
	{ short: 'SME', long: 'Subject Matter Expert' },
	{ short: 'SMM', long: 'Safe Management Measures' },
	{ short: 'SMM', long: 'Senior Management Meeting' },
	{ short: 'SMR', long: 'Senior Management Retreat' },
	{ short: 'SMS', long: 'Standard Market Solution' },
	{ short: 'SMS', long: 'Senior Minister of State' },
	{ short: 'SMile', long: 'Service - Going the extra MILE' },
	{ short: 'SNDG', long: 'Smart Nation Digital Government' },
	{ short: 'SNDGG', long: 'Smart Nation and Digital Government Group' },
	{ short: 'SNDGO', long: 'Smart Nation and Digital Government Office' },
	{ short: 'SNIW', long: 'Smart Nation Innovations Week' },
	{ short: 'SNOC', long: 'Singapore National Olympic Council' },
	{ short: 'SNP', long: 'Strategic National Project' },
	{ short: 'SNPC', long: 'Singapore National Paralympic Council' },
	{ short: 'SNS', long: 'Social Network Site' },
	{ short: 'SNSP', long: 'Smart Nation Sensor Platform' },
	{ short: 'SOA', long: 'Service-Oriented Architecture' },
	{ short: 'SOAP', long: 'Simple Object Access Protocol' },
	{ short: 'SOAR', long: 'Security Operations, Automation and Response' },
	{ short: 'SOC', long: 'Special Operations Command' },
	{ short: 'SOE', long: 'Standard ICT Operating Environment' },
	{ short: 'SOLL', long: 'Smart Office Living Lab' },
	{ short: 'SOM', long: 'Service and Ops Management' },
	{ short: 'SOP', long: 'Standard Operating Procedure' },
	{ short: 'SOW', long: 'Statement Of Work' },
	{ short: 'SOW', long: 'Scope Of Work' },
	{ short: 'SOW', long: 'Scheme Of Work' },
	{ short: 'SP', long: 'Standard Products' },
	{ short: 'SP', long: 'Singapore Polytechnic' },
	{ short: 'SPCP', long: 'SingPass/CorpPass' },
	{ short: 'SPEAR', long: 'Singapore Prisons Emergency Action Response' },
	{ short: 'SPEAR', long: 'Security policy Enforcement and regulation' },
	{ short: 'SPF', long: 'Singapore Police Force' },
	{ short: 'SPIS', long: 'Supplier Performance Information System' },
	{ short: 'SPORTSG', long: 'Sport Singapore' },
	{ short: 'SPRC', long: 'Security Policy Review Committee' },
	{ short: 'SPS', long: 'Singapore Prison Service' },
	{ short: 'SPS', long: 'Singapore Public Service' },
	{ short: 'SPSL', long: 'Senior Public Service Leaders' },
	{ short: 'SPSL', long: 'Senior Public Service Leadership' },
	{ short: 'SQA', long: 'Singapore Quality Award' },
	{ short: 'SQC', long: 'Singapore Quality Class' },
	{ short: 'SQL', long: 'Structured Query Language' },
	{ short: 'SRT', long: 'Suriname Time' },
	{ short: 'SSD', long: 'Standard Stamp Duty' },
	{ short: 'SSEB', long: 'Safety, Security and Emergency Branch' },
	{ short: 'SSG', long: 'SkillsFuture Singapore' },
	{ short: 'SSH', long: 'Secure Shell' },
	{ short: 'SSICT', long: 'Social Service ICT Program Office' },
	{ short: 'SSO', long: 'Singapore Symphony Orchestra' },
	{ short: 'SSOT', long: 'Single Source Of Truth' },
	{ short: 'SSS', long: 'Staff Suggestion Scheme' },
	{ short: 'SSSO', long: 'Senior Specialist Staff Officer' },
	{ short: 'SST', long: 'Samoa Standard Time' },
	{ short: 'SST', long: 'Singapore Standard Time' },
	{ short: 'ST', long: 'Singapore Technologies' },
	{ short: 'STA', long: 'Short term accommodation' },
	{ short: 'STATECOURTS', long: 'State Courts Singapore' },
	{ short: 'STB', long: 'Singapore Tourism Board' },
	{ short: 'STFP', long: 'SSH File Transfer Protocol' },
	{ short: 'STG', long: 'Sectoral Transformation Group' },
	{
		short: 'STRIDE',
		long: 'Spoofing, Tampering, Repudiation, Information disclosure, Denial of Service, Elevation of Privilege',
	},
	{ short: 'SUD', long: 'Senior User Dialogue' },
	{ short: 'SUH', long: 'Smart Urban Habitat' },
	{ short: 'SVIP', long: 'Smart Visa for Identification with Passport' },
	{ short: 'SVP', long: 'Small Value Purchase' },
	{ short: 'SWG', long: 'Secure Walled Garden' },
	{ short: 'SWOT', long: 'Strengths, Weaknesses, Opportunities, Threats' },
	{ short: 'SWP', long: 'Strategic Workforce Plan' },
	{ short: 'SWP', long: 'Service Wide Programme' },
	{ short: 'SWTA', long: 'Service Wide Technical Architecture' },
	{ short: 'SY', long: 'Scholarship Year' },
	{ short: 'SaaS', long: 'Software as a service' },
	{ short: 'Spml', long: 'Service Provisioning Markup Language' },
	{ short: 'TAA', long: 'Tender Approving Authority' },
	{ short: 'TAC', long: 'Threat Analysis Centre' },
	{ short: 'TAF', long: 'Technical Architectural Forum' },
	{ short: 'TAFEP', long: 'Tripartite Alliance for Fair and Progressive Employment Practices' },
	{ short: 'TAL', long: 'Token Assisted Login' },
	{ short: 'TAS', long: 'Telecommunication Authority of Singapore' },
	{ short: 'TASS', long: 'Training Award & Sponsorship Scheme' },
	{ short: 'TAT', long: 'Turn-Around-Time' },
	{ short: 'TCP/IP', long: 'Tranmission Control Protocol/Internet Protocol' },
	{ short: 'TEC', long: 'Tender Evaluation Committee' },
	{ short: 'TEP', long: 'Technology Experimentation Program' },
	{ short: 'TERR', long: 'Tender Evaluation Recommendation Report' },
	{ short: 'TG', long: 'Training Guidance' },
	{ short: 'TGIF', long: "Thank God It's Friday" },
	{ short: 'THA', long: 'Thailand Standard Time' },
	{ short: 'TIC', long: 'Trade & Industry Cluster' },
	{ short: 'TIG', long: 'Technology Infrastructure Group' },
	{ short: 'TIH', long: 'Tourism Information & Services Hub' },
	{ short: 'TIL', long: 'Today I Learned' },
	{ short: 'TIVO', long: 'Temp, Intern, Vendor and Others' },
	{ short: 'TKT', long: 'Tokelau Time' },
	{ short: 'TLDR', long: 'Too Long, Didnt Read' },
	{ short: 'TLP', long: 'Total Learning Plan' },
	{ short: 'TLS', long: 'Telecom Licensing System Portal' },
	{ short: 'TLT', long: 'Timor Leste Time' },
	{ short: 'TM', long: 'Tamil Murasu' },
	{ short: 'TMI', long: 'Too Much Information' },
	{ short: 'TMS', long: 'Transportation Management System' },
	{ short: 'TMS', long: 'Talent Management System' },
	{ short: 'TMT', long: 'Tenant Management Tier, AIAS' },
	{ short: 'TNP', long: 'The New Paper' },
	{ short: 'TNS', long: 'Training Nomination System' },
	{ short: 'TO', long: 'Transformation Office' },
	{ short: 'TOP', long: 'Temporary Occupation Permit' },
	{ short: 'TOR', long: 'Terms Of Reference' },
	{ short: 'TOT', long: 'Tonga Time' },
	{ short: 'TP', long: 'Temasek Polytechnic' },
	{ short: 'TRA', long: 'Threat Risk Analysis' },
	{ short: 'TRACE', long: 'The Repository of MHA Enterprise Architecture' },
	{ short: 'TRL', long: 'Technology Readiness Level' },
	{ short: 'TRT', long: 'Turkey Time' },
	{ short: 'TS', long: 'Technical services' },
	{ short: 'TSC', long: 'Technical Services Consultant' },
	{ short: 'TSF', long: 'Transformation Support Fund' },
	{ short: 'TSM', long: 'Technical Services Manager' },
	{ short: 'TT', long: 'TraceTogether' },
	{ short: 'TTDS', long: 'Translation Talent Development Scheme' },
	{ short: 'TTX', long: 'Table Top Exercise' },
	{ short: 'TeNHP', long: 'Technology Enabled National Healthy Population' },
	{ short: 'UAT', long: 'User Acceptance Test' },
	{ short: 'UC', long: 'Usability Checklist' },
	{ short: 'UEN', long: 'Unique Entity Number' },
	{ short: 'UI', long: 'User Interface' },
	{ short: 'ULAST', long: 'Ulaanbaatar Summer Time' },
	{ short: 'ULO', long: 'University Liaison Officer' },
	{ short: 'UMTS', long: 'Universal Mobile Telephone Service' },
	{ short: 'UNESCO', long: 'United Nations Educational, Scientific and Cultural Organization' },
	{ short: 'UP', long: 'Unsatisfactory Performer' },
	{ short: 'UPLIFT', long: 'Uplifting Pupils in Life and Inspiring Families Taskforce' },
	{ short: 'URA', long: 'Urban Redevelopment Authority' },
	{ short: 'URL', long: 'Uniform Resource Locator' },
	{ short: 'USB', long: 'Universal Serial Bus' },
	{ short: 'USZ1', long: 'Kaliningrad Time' },
	{ short: 'UTC', long: 'Coordinated Universal Time' },
	{ short: 'UX', long: 'User eXperience' },
	{ short: 'UYST', long: 'Uruguay Summer Time' },
	{ short: 'UYT', long: 'Uruguay Standard Time' },
	{ short: 'UZT', long: 'Uzbekistan Time' },
	{ short: 'VA', long: 'Value Added' },
	{ short: 'VA', long: 'Vulnerability Assessment' },
	{ short: 'VAPT', long: 'Vulnerability Assessment and Penetration Testing' },
	{ short: 'VAS', long: 'Values and Attitudes Survey' },
	{ short: 'VB', long: 'Variable Bonus' },
	{ short: 'VC', long: 'Variable Component' },
	{ short: 'VDC', long: 'Virtual Design and Construction' },
	{ short: 'VDS', long: 'Vaccination-Differentiated Safe Management Measures' },
	{ short: 'VET', long: 'Venezuelan Standard Time' },
	{ short: 'VFM', long: 'Virtual File Manager' },
	{ short: 'VIA', long: 'Values in Action' },
	{ short: 'VIS', long: 'Visual Identity System' },
	{ short: 'VLAT', long: 'Vladivostok Time' },
	{ short: 'VM', long: 'Virtual Machine' },
	{ short: 'VMS', long: 'Visitor Management System' },
	{ short: 'VMS', long: 'Vulnerability Management Service' },
	{ short: 'VOIP', long: 'Voice Over Internet Protocol' },
	{ short: 'VPA', long: 'Vice-Principal' },
	{ short: 'VPC', long: 'Virtual Private Cloud' },
	{ short: 'VPIS', long: 'Vendor Performation Information System' },
	{ short: 'VPN', long: 'Virtual Private Network' },
	{ short: 'VPPW', long: 'Volunteer Public Path Warden' },
	{ short: 'VR', long: 'Virtual Reality' },
	{ short: 'VTL', long: 'Vaccinated Travel Lane' },
	{ short: 'VUCA', long: 'Volatile Uncertain Complex and Ambiguity' },
	{ short: 'VWO', long: 'Voluntary Welfare Organisation' },
	{ short: 'WAF', long: 'Web Application Firewall' },
	{ short: 'WAST', long: 'West Africa Summer Time' },
	{ short: 'WAT', long: 'West Africa Time' },
	{ short: 'WBN', long: 'Wireless Broadbank Network' },
	{ short: 'WCRSG', long: 'Walk Cycle Ride Singapore' },
	{ short: 'WDA', long: 'Singapore Workforce Development Agency' },
	{ short: 'WEAVE', long: 'Web Services Add Value to Enterprise' },
	{ short: 'WEF', long: 'World Economic Forum' },
	{ short: 'WEST', long: 'Western European Summer Time' },
	{ short: 'WET', long: 'Western European Time' },
	{ short: 'WHAM', long: 'Website High Availability Monitoring' },
	{ short: 'WIP', long: 'Work In Progress' },
	{ short: 'WIS', long: 'Web Interface Standards' },
	{ short: 'WIT', long: 'Western Indonesian Time' },
	{ short: 'WITSA', long: 'World IT & Services Alliance' },
	{ short: 'WLTD', long: 'Work Learn Technical Diploma' },
	{ short: 'WOG', long: 'Whole0Of-Government' },
	{ short: 'WOGAA', long: 'Whole-Of-Government Application Analytics' },
	{ short: 'WOGSO', long: 'Whole-of-Government Strategic Outcomes' },
	{ short: 'WPC', long: 'Workforce Planning & Capabilities' },
	{ short: 'WR/DF', long: 'Work Review/Development Form' },
	{ short: 'WSG', long: 'Workforce Singapore' },
	{ short: 'WSH', long: 'Workplace Safety and Health' },
	{ short: 'WSMC', long: 'Whole of Government Sensor Master Planner Committee' },
	{ short: 'WSQ', long: 'Workforce Skills Qualification' },
	{ short: 'WST', long: 'Western Standard Time' },
	{ short: 'WTE', long: 'Waste to Energy' },
	{ short: 'WTO', long: 'World Trade Organisation' },
	{ short: 'WYSIWYG', long: 'What You See is What You Get' },
	{ short: 'YAKT', long: 'Yakutsk Time' },
	{ short: 'e-BIDS', long: 'e-Business Industry Development Scheme' },
	{ short: 'e-Celebrations', long: 'An annual e-lifestyle campaign' },
	{ short: 'eGAP', long: 'e-Government Action Plan' },
	{ short: 'eGPC', long: 'eGovernment Policy Committee' },
	{ short: 'eIMS', long: 'Enterprise Information Management System' },
	{ short: 'gSMS', long: 'Government Short Message Service' },
	{ short: 'i-Caf', long: 'Innovation Caf' },
	{ short: 'iAMS', long: "GovTech's Asset Management System" },
	{ short: 'iLIUP', long: 'Infocomm Local Industry Upgrading Programme' },
	{ short: 'iN 2015', long: 'Intelligent Nation 2015' },
	{ short: 'iTRAIN', long: 'Infocomm Training Resources And Incentives on the Net' },
];
